
class Error(Exception):
    pass


class BoundsError(Error):
    pass
